"use strict";
exports.__esModule = true;
var circle_1 = require("./circle");
var rectangle_1 = require("./rectangle");
var circleObj = new circle_1.circle(3);
circleObj.Myarea();
circleObj.Display();
var rectObj = new rectangle_1.Rectangle(3, 4);
rectObj.Myarea();
rectObj.Display();
